"""Add level class

Revision ID: 8691ae9b02f0
Revises: 
Create Date: 2019-06-26 11:46:10.033828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8691ae9b02f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_level_key', 'users', type_='unique')
    op.create_foreign_key(None, 'users', 'level', ['level'], ['level'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_unique_constraint('users_level_key', 'users', ['level'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    # ### end Alembic commands ###
