"""Pending

Revision ID: ddb213ef8010
Revises: 2e5692c65b97
Create Date: 2019-07-02 09:21:11.981455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddb213ef8010'
down_revision = '2e5692c65b97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farm', sa.Column('pending', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farm', 'pending')
    # ### end Alembic commands ###
